### ISSUE TITLE
Issues in todo app

### ISSUE THREAD

**Issue by Uzmakh** [usama7365/developer-community#10]
<img width="914" alt="todo-issues" src="https://github.com/user-attachments/assets/1ed5cc24-dcbf-4989-ab7b-a5010598d18b">
All strikethrough when clicking on complete button.
I send you repo link...check the js code there.
 clear all button is working fine. Kindly check theShuffle and move up and down buttons>
 Local storage code also working fine.
 https://github.com/Uzmakh/ToDoList-App

**Comment by usama7365** [comment]
Did you push the latest code on [https://github.com/Uzmakh/ToDoList-App](https://github.com/Uzmakh/ToDoList-App)

**Comment by Uzmakh** [comment]
Yes , I did.

**Comment by usama7365** [comment]
sure let me check

**Comment by Uzmakh** [comment]
Thanks, Kindly when you correct the code, comment the reasons for errors.(for my learning)

**Comment by usama7365** [comment]
@Uzmakh kindly add me as collaborator to push the lastest code in repo. 
Bug resolved
[ToDoList-App.zip](https://github.com/user-attachments/files/16637668/ToDoList-App.zip)


Thanks
