### ISSUE TITLE
Not fetching the conversation on frontend 

### ISSUE THREAD

**Issue by VisalRazaZaidi** [usama7365/developer-community#11]
**Describe the bug**
not fetching the conversations on frontend 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'useGetConversation.jsx (where you find the fetch URL )' after starting both server frontend or backend
2. do login (username:visalraza password:123456)
3. open the inspect element and on the network panel you see the error of fetch issue of conversation 

**Expected behaviour**
I want that conversation on the database will get fetched from a URL and appears on frontend in sidebar 

**Screenshots**
![Inspect Element SS](https://github.com/user-attachments/assets/30e74e55-1544-4eb2-bc3b-c2190979ddb3)
![Coversations_Result  ](https://github.com/user-attachments/assets/bfcfb1c8-cb37-4fb2-a06c-416855a0dd46)
☝this should be the result 

**Additional context**

I'm creating a Chat App on MERN Stack and the problem that I'm facing is I want to show conversations which are stored in database 

Repo link : https://github.com/VisalRazaZaidi/Chat_app

**Comment by usama7365** [comment]
Hi @VisalRazaZaidi ,

Thank you for bringing this issue to my attention. I noticed that the repository link you provided is set to private. Could you please make the repository public or share access with me so I can take a closer look at the code and help you resolve the issue?

Looking forward to your response!

Best regards,
Usama Aamir(Feline preditor)

**Comment by VisalRazaZaidi** [comment]
repository in now public

**Comment by VisalRazaZaidi** [comment]
i debugged by myself thank you for time bro🥰
