### ISSUE TITLE
need help in API integration

### ISSUE THREAD

**Issue by haniya-Dev** [usama7365/developer-community#14]
facing issue to fetch products from api

**Comment by usama7365** [comment]
const productsContainer = document.getElementById("productsContainer");

async function fetchProducts() {
  try {
    const response = await fetch("https://api.example.com/products");
    
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    
    const products = await response.json();
    displayProducts(products);
  } catch (error) {
    console.error("Failed to fetch products:", error);
  }
}

function displayProducts(products) {
  productsContainer.innerHTML = products
    .map(
      (product) => `
        <div class="product-card">
          <h3>${product.name}</h3>
          <p>${product.description}</p>
          <p>Price: $${product.price}</p>
        </div>
      `
    )
    .join("");
}

// Call the function to fetch and display products
fetchProducts();

**Comment by haniya-Dev** [comment]
thank you
