### ISSUE TITLE
dashboard order not update or remove 

### ISSUE THREAD

**Issue by Zainali005** [usama7365/developer-community#16]
"use server";
import React from "react";
import Orders from "./Orders";
import { client } from "@/lib/redis";
import axios from "axios";
import { cookies } from "next/headers";
import Menu from "@/components/Menu";

function getLoggedInUserId() {
  const cookieStore = cookies();
  const userId = cookieStore.get("userId");
  return userId ? userId.value : null;
}
async function fetchOrders(loggedInUserId: string) {
  let orders = [];

  try {
    const keys = await client.keys(`orders:${loggedInUserId}:order:*`);
    const redisOrdersData = await Promise.all(
      keys.map((key) => client.hGetAll(key))
    );

    if (redisOrdersData.length > 0) {
      orders = redisOrdersData.map((data) => {
        const order = {};
        for (const [key, value] of Object.entries(data)) {
          try {
            order[key] = JSON.parse(value);
          } catch {
            order[key] = value;
          }
        }
        return order;
      });

    } else {
      const storeKeys = await client.keys("store:*");
      const stores = await Promise.all(
        storeKeys.map((key) => client.hGetAll(key))
      );
      const fallbackImageUrl =
        "https://static.vecteezy.com/system/resources/thumbnails/022/014/063/small_2x/missing-picture-page-for-website-design-or-mobile-app-design-no-image-available-icon-vector.jpg";

      const userStores = stores.filter(
        (store) => store.userid === loggedInUserId
      );

      const fetchOrdersPromises = userStores.map(async (store) => {
        const requestOptions = {
          headers: {
            "Content-Type": "application/json",
            "X-Shopify-Access-Token": store.token,
          },
        };

        try {
          const response = await axios.get(
            `https://${store.shop}/admin/api/2024-01/orders.json`,
            requestOptions
          );

          const resp = response.data;
          console.log(resp, "response directly from shopify");

          if (!resp.orders || !Array.isArray(resp.orders)) {
            return [];
          }
          const storeOrders = await Promise.all(
            resp.orders.map(async (order) => {
              if (order.line_items.length > 0) {
                const url = `https://${store.shop}/admin/api/2024-01/products/${order.line_items[0].product_id}/images.json`;
                try {
                  const imageResponse = await axios.get(url, requestOptions);
                  const imgRes = imageResponse.data;
                  const imgSrc = imgRes.images[0]?.src || fallbackImageUrl;
                  return { ...order, imgSrc };
                } catch {
                  return { ...order, imgSrc: fallbackImageUrl };
                }
              } else {
                return { ...order, imgSrc: fallbackImageUrl };
              }
            })
          );
          return storeOrders;
        } catch {
          return [];
        }
      });

      const fetchedOrders = await Promise.all(fetchOrdersPromises);
      orders = fetchedOrders.flat();
      await synchronizeOrders(orders, loggedInUserId);
    }
  } catch {
    return [];
  }

  const uniqueOrders = orders.filter(
    (order, index, self) => index === self.findIndex((o) => o.id === order.id)
  );

  return uniqueOrders;
}
async function synchronizeOrders(fetchedOrders: any, loggedInUserId: any) {
  try {
    const existingKeys = await client.keys(`order:${loggedInUserId}:*`);
    const existingOrdersData = await Promise.all(
      existingKeys.map((key) => client.get(key))
    );
    const existingOrders = existingOrdersData.map((data) => JSON.parse(data));
    const existingOrdersMap = new Map(
      existingOrders.map((order) => [order.id, order])
    );
    const ordersToUpdate = fetchedOrders.filter((order: any) => {
      const existingOrder = existingOrdersMap.get(order.id);
      return (
        !existingOrder ||
        JSON.stringify(existingOrder) !== JSON.stringify(order)
      );
    });

    const ordersToRemove = existingOrders.filter((existingOrder) => {
      return !fetchedOrders.find((order: any) => order.id === existingOrder.id);
    });
    const order = ordersToUpdate.map((order) => order.id);
    console.log(order);

    if (ordersToUpdate.length > 0) {
      for (const order of ordersToUpdate) {
        const orderKey = `orders:${loggedInUserId}:order:${order.id}`;
        const orderData = [];
        for (const key in order) {
          if (order.hasOwnProperty(key)) {
            orderData.push(key, JSON.stringify(order[key]));
          }
        }

        try {
          await client.HSET(orderKey, orderData);
        } catch (error) {
          console.error(`Error setting hash for order ${orderKey}:`, error);
        }
      }
    }

    if (ordersToRemove.length > 0) {
      for (const order of ordersToRemove) {
        await client.del(`orders:${loggedInUserId}:${order.id}`);
      }
    }
  } catch (error) {
    console.error("Error synchronizing orders:", error);
  }
}

export default async function Page() {
  const loggedInUserId = getLoggedInUserId();

  if (!loggedInUserId) {
    return (
      <div>
        <Menu selectedTab="new" setSelectedTab={() => { }} />
        <p className="flex justify-center text-3xl text-red-600 font-inter font-bold">
          User not logged in!
        </p>
      </div>
    );
  }

  const orders = await fetchOrders(loggedInUserId);

  return <Orders orders={orders} />;
}

this is the dashboard component where if i create or remove order then not adding or removing from dashboard untill i delete the redis data

**Comment by usama7365** [comment]
This sounds like the synchronization between your Redis store and your frontend isn’t working as expected. To fix this, you need to ensure that your `synchronizeOrders` function correctly updates and removes orders in Redis whenever changes occur. I noticed a few areas where the logic might need some tweaking.

Here’s how you can refine the code:

1. **Update Orders:** 
   - Ensure the updated orders are correctly pushed to Redis by using `HSET` (or `HDEL` to remove specific fields if needed).
   - Add or update the existing order in Redis with the new data.

2. **Remove Orders:**
   - Make sure to delete the orders from Redis that no longer exist after the synchronization.

### Updated Code Snippet:

```javascript
async function synchronizeOrders(fetchedOrders: any, loggedInUserId: any) {
  try {
    const existingKeys = await client.keys(`orders:${loggedInUserId}:order:*`);
    const existingOrdersData = await Promise.all(
      existingKeys.map((key) => client.hGetAll(key))
    );
    const existingOrdersMap = new Map(
      existingOrdersData.map((order) => [order.id, order])
    );

    const ordersToUpdate = fetchedOrders.filter((order: any) => {
      const existingOrder = existingOrdersMap.get(order.id);
      return (
        !existingOrder ||
        JSON.stringify(existingOrder) !== JSON.stringify(order)
      );
    });

    const ordersToRemove = Array.from(existingOrdersMap.values()).filter(
      (existingOrder) => {
        return !fetchedOrders.find((order: any) => order.id === existingOrder.id);
      }
    );

    // Update or Add New Orders
    if (ordersToUpdate.length > 0) {
      for (const order of ordersToUpdate) {
        const orderKey = `orders:${loggedInUserId}:order:${order.id}`;
        const orderData = [];
        for (const key in order) {
          if (order.hasOwnProperty(key)) {
            orderData.push(key, JSON.stringify(order[key]));
          }
        }
        try {
          await client.hSet(orderKey, ...orderData);
        } catch (error) {
          console.error(`Error setting hash for order ${orderKey}:`, error);
        }
      }
    }

    // Remove Deleted Orders
    if (ordersToRemove.length > 0) {
      for (const order of ordersToRemove) {
        const orderKey = `orders:${loggedInUserId}:order:${order.id}`;
        try {
          await client.del(orderKey);
        } catch (error) {
          console.error(`Error deleting order ${orderKey}:`, error);
        }
      }
    }
  } catch (error) {
    console.error("Error synchronizing orders:", error);
  }
}
```

### Summary of Changes:
- **Order Updates:** Ensuring `hSet` is used to store the orders efficiently in Redis.
- **Order Removal:** Properly identifying and removing orders that no longer exist.

### Additional Consideration:
If your orders aren’t being fetched or synchronized as expected, you might want to double-check the `fetchOrders` function and the order keys you're working with.

Give these changes a shot, and let me know if the dashboard updates as expected after this!

Cheers,
Feline Predator

**Comment by Zainali005** [comment]
not working

**Comment by usama7365** [comment]
i think we need to review all code come to anydesk today mid night

**Comment by Zainali005** [comment]
Please give me some time to sort out the issue I'm facing. I will be working on it starting tomorrow. In the meantime, have a rest.
