### ISSUE TITLE
Fix the bugs in age calculator

### ISSUE THREAD

**Issue by Uzmakh** [usama7365/developer-community#17]
[ageCalc.zip](https://github.com/user-attachments/files/16816907/ageCalc.zip)

**Comment by Uzmakh** [comment]
<img width="368" alt="Capture-3" src="https://github.com/user-attachments/assets/307ff98e-0adc-4860-9f69-eb7f73790efa">
 the code is working for some dates and for some not.

**Comment by Uzmakh** [comment]
https://github.com/user-attachments/assets/91aabd0a-9c7d-4ddc-a5bc-c0f90d476ec8

**Comment by usama7365** [comment]
[ageCalc.zip](https://github.com/user-attachments/files/16823449/ageCalc.zip)

done I am just complete it please review the code i just drop commits as well for better code understanding 
Thanks

**Comment by Uzmakh** [comment]
Thanks for all.
