### ISSUE TITLE
Tooltip Issue in chart using recharts library

### ISSUE THREAD

**Issue by Afif-Ur-Rahman** [usama7365/developer-community#18]
When the dot in the chart is hovered I want to show the tooltip above that dot. 
![image](https://github.com/user-attachments/assets/f4d83aee-8ffb-4ff6-b59b-effbf0e1ef91)
but in my case when the line in the chart is hovered it shows the tooltip. 
![image](https://github.com/user-attachments/assets/48ab76c4-cf10-4ecf-a185-078a986bb3b5)

this is the code for chart >>
`import { Flex, Text } from '@radix-ui/themes'
import {
  CartesianGrid,
  Line,
  LineChart,
  ReferenceArea,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts'

const TooltipData = ({
  active,
  payload,
}: {
  active: boolean | undefined
  payload: { TotalScore: number; 'Date/Time': string }
}) => {

  if (active && payload) {
    return (
      <Flex
        direction="column"
        justify="center"
        align="center"
        className="text-white bg-black border-black rounded-2 p-2"
      >
        <Text>{`Score: ${payload.TotalScore}`}</Text>
        <Text>{`Time: ${payload['Date/Time']}`}</Text>
      </Flex>
    )
  }
  return null
}

const Chart = () => {

  const data = [
    {
      'Date/Time': '2024-09-30 10:00',
      Note: 'Out Pt, New Pt, In-Person',
      FilledBy: 'Provider',
      TotalScore: '12',
      AddToNote: false,
    },
    {
      'Date/Time': '2024-09-30 10:00',
      Note: 'Out Pt, New Pt, In-Person',
      FilledBy: 'Provider',
      TotalScore: '7',
      AddToNote: false,
    },
    {
      'Date/Time': '2024-09-30 10:00',
      Note: 'Out Pt, New Pt, In-Person',
      FilledBy: 'Provider',
      TotalScore: '18',
      AddToNote: false,
    },
    {
      'Date/Time': '2024-09-30 10:00',
      Note: 'Out Pt, New Pt, In-Person',
      FilledBy: 'Provider',
      TotalScore: '13',
      AddToNote: false,
    },
    {
      'Date/Time': '2024-09-30 10:00',
      Note: 'Out Pt, New Pt, In-Person',
      FilledBy: 'Provider',
      TotalScore: '23',
      AddToNote: false,
    },
    {
      'Date/Time': '2024-09-30 10:00',
      Note: 'Out Pt, New Pt, In-Person',
      FilledBy: 'Provider',
      TotalScore: '19',
      AddToNote: false,
    },
    {
      'Date/Time': '2024-09-30 10:00',
      Note: 'Out Pt, New Pt, In-Person',
      FilledBy: 'Provider',
      TotalScore: '11',
      AddToNote: false,
    },
    {
      'Date/Time': '2024-09-30 10:00',
      Note: 'Out Pt, New Pt, In-Person',
      FilledBy: 'Provider',
      TotalScore: '21',
      AddToNote: false,
    },
    {
      'Date/Time': '2024-09-30 10:00',
      Note: 'Out Pt, New Pt, In-Person',
      FilledBy: 'Provider',
      TotalScore: '6',
      AddToNote: false,
    },
    {
      'Date/Time': '2024-09-30 10:00',
      Note: 'Out Pt, New Pt, In-Person',
      FilledBy: 'Provider',
      TotalScore: '14',
      AddToNote: false,
    },
  ]

  return (
    <ResponsiveContainer width="100%" height={400} className="-ml-[50px]">
      <LineChart data={data} margin={{ top: 20, right: 20, bottom: 40 }}>
        <ReferenceArea y1={20} y2={27} fill="rgba(229, 72, 77, 0.2)" />
        <ReferenceArea y1={10} y2={20} fill="rgba(253, 255, 0, 0.2)" />
        <ReferenceArea y1={5} y2={10} fill="rgba(48, 164, 108, 0.2)" />
        <CartesianGrid vertical={false} />
        <XAxis
          dataKey="Date/Time"
          interval={0}
          tickMargin={10}
          tickSize={10}
          axisLine={false}
        />
        <YAxis
          domain={[0, 27]}
          ticks={[0, 2.5, 5, 7.5, 10, 12.5, 15, 17.5, 20, 22.5, 25, 27]}
          interval={0}
          axisLine={false}
          tickLine={false}
        />
        <Tooltip
          content={({ active, payload }) => (
            <TooltipData active={active} payload={payload?.[0]?.payload} />
          )}
          cursor={false}
          filterNull={true}
        />
        <Line
          type="monotone"
          dataKey="TotalScore"
          stroke="black"
          strokeWidth={3}
          dot={{ r: 6, fill: 'black' }}
          activeDot={{ r: 6, stroke: 'black' }}
        />
      </LineChart>
    </ResponsiveContainer>
  )
}

export { Chart }
`

**Comment by usama7365** [comment]
You need to adjust the behavior of the `Tooltip` and ensure the `activeDot` property is set correctly. Currently, the tooltip is being triggered by hovering over the entire line rather than just the dots.

Here's how you can modify the `LineChart` and `Tooltip` to achieve this:

1. **Set the `isAnimationActive` to `false`** in the `Line` component to ensure the tooltip appears only on the dot and does not animate between lines.
2. **Ensure that the tooltip cursor is active only when hovering over the dots** by making sure that the `activeDot` is explicitly set.

Here’s the updated code:

```tsx
import { Flex, Text } from '@radix-ui/themes'
import {
  CartesianGrid,
  Line,
  LineChart,
  ReferenceArea,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts'

const TooltipData = ({
  active,
  payload,
}: {
  active: boolean | undefined
  payload: { TotalScore: number; 'Date/Time': string }
}) => {

  if (active && payload) {
    return (
      <Flex
        direction="column"
        justify="center"
        align="center"
        className="text-white bg-black border-black rounded-2 p-2"
      >
        <Text>{`Score: ${payload.TotalScore}`}</Text>
        <Text>{`Time: ${payload['Date/Time']}`}</Text>
      </Flex>
    )
  }
  return null
}

const Chart = () => {

  const data = [
    {
      'Date/Time': '2024-09-30 10:00',
      Note: 'Out Pt, New Pt, In-Person',
      FilledBy: 'Provider',
      TotalScore: '12',
      AddToNote: false,
    },
    // Add the rest of the data points...
  ]

  return (
    <ResponsiveContainer width="100%" height={400} className="-ml-[50px]">
      <LineChart data={data} margin={{ top: 20, right: 20, bottom: 40 }}>
        <ReferenceArea y1={20} y2={27} fill="rgba(229, 72, 77, 0.2)" />
        <ReferenceArea y1={10} y2={20} fill="rgba(253, 255, 0, 0.2)" />
        <ReferenceArea y1={5} y2={10} fill="rgba(48, 164, 108, 0.2)" />
        <CartesianGrid vertical={false} />
        <XAxis
          dataKey="Date/Time"
          interval={0}
          tickMargin={10}
          tickSize={10}
          axisLine={false}
        />
        <YAxis
          domain={[0, 27]}
          ticks={[0, 2.5, 5, 7.5, 10, 12.5, 15, 17.5, 20, 22.5, 25, 27]}
          interval={0}
          axisLine={false}
          tickLine={false}
        />
        <Tooltip
          content={({ active, payload }) => (
            <TooltipData active={active} payload={payload?.[0]?.payload} />
          )}
          cursor={false}
          filterNull={true}
        />
        <Line
          type="monotone"
          dataKey="TotalScore"
          stroke="black"
          strokeWidth={3}
          dot={{ r: 6, fill: 'black' }}  // Ensure that dots are visible
          activeDot={{ r: 8, fill: 'black', stroke: 'white', strokeWidth: 2 }}  // Highlight the dot when hovered
          isAnimationActive={false}  // Disable line hover animation
        />
      </LineChart>
    </ResponsiveContainer>
  )
}

export { Chart }
```

### Key Changes:
1. **`isAnimationActive={false}`**: Disabling the line hover animation ensures the tooltip is displayed only when hovering over the dots and not when hovering over the line.
2. **`activeDot` Styling**: I've added a larger active dot with a white stroke to make it stand out when hovered, so it’s clearer where the user is hovering.
3. **Tooltip customization**: The `cursor={false}` setting ensures that no hover cursor appears over the line, focusing interaction only on the dots.
