### ISSUE TITLE
Website deployement on Vercel Issue 

### ISSUE THREAD

**Issue by waris64** [usama7365/developer-community#2]
Problem: 
I am facing Issue with the deployement of my React App on the vercel.First there was the folder structure issue . Now, I have solved that with the help of @usama7365   but I am still facing issue in deployement.
![Screenshot (791)](https://github.com/user-attachments/assets/f31ad5db-91c6-4b4c-80e3-82006c8c6f24)

**Comment by Zainali005** [comment]
make sure to add vercel.json and again retry and add the env data as well in vercel with enviroment

**Comment by usama7365** [comment]
kindly check your vercel terminal logs. if issue presist then come to anydesk 😊

**Comment by waris64** [comment]
> make sure to add vercel.json and again retry and add the env data as well in vercel with enviroment

Added already .

**Comment by waris64** [comment]
> kindly check your vercel terminal logs. if issue presist then come to anydesk 😊
Here is the logs screenshot . 
![image](https://github.com/user-attachments/assets/7eaab2fd-e8fa-4566-b573-d151f9ead1ff)

**Comment by Zainali005** [comment]
> > make sure to add vercel.json and again retry and add the env data as well in vercel with enviroment
> 
> Added already . Further If you want to look the code here is the Repository Url https://github.com/waris64/ShoppingGo

how you can run this in your project pakage.json is missing check ?

**Comment by usama7365** [comment]
@waris64 if issue presist then come to any desk thanks

**Comment by waris64** [comment]
> > > make sure to add vercel.json and again retry and add the env data as well in vercel with enviroment
> > 
> > 
> > Added already . Further If you want to look the code here is the Repository Url https://github.com/waris64/ShoppingGo
> 
> how you can run your project pakage.json is missing check ?

I have set that issue as well :)

**Comment by Zainali005** [comment]
> > > > make sure to add vercel.json and again retry and add the env data as well in vercel with enviroment
> > > 
> > > 
> > > Added already . Further If you want to look the code here is the Repository Url https://github.com/waris64/ShoppingGo
> > 
> > 
> > how you can run your project pakage.json is missing check ?
> 
> I have set that issue as well :)

still i din't see you pakage.json in your git repository

**Comment by usama7365** [comment]
https://github.com/usama7365/waris-issue 

@waris64  issue resolved 👌

**Comment by usama7365** [comment]
issue resolved 👌
