### ISSUE TITLE
Send props from parent to child 

### ISSUE THREAD

**Issue by quratulainaqeel** [usama7365/developer-community#3]
send specific blog data from the parent component (where all blogs show) to the child component (specific blog page) page in Next.js 14.

**Comment by Zainali005** [comment]
Can you provide more context and code to solve the issue?

**Comment by usama7365** [comment]
issue resolved @quratulainaqeel 
[Feline.zip](https://github.com/user-attachments/files/16401706/Feline.zip)

**Comment by usama7365** [comment]
issue resolved 👌
