### ISSUE TITLE
i want to update the redis data 

### ISSUE THREAD

**Issue by Zainali005** [usama7365/developer-community#4]
i have redis data in my db (imageUrl,uuid,variant,sticker-sheet,status,type,size,price,userId,sku)
i have call the api for fetch data in frontend and display in my frontend there is a form which contains name and description when user add name and description i want to update the redis data and my redis data is in hashes . How to do this 

api:
import { client } from "@/lib/redis";
import { NextRequest, NextResponse } from "next/server";
import { v4 as uuidv4 } from "uuid";

export async function POST(req: NextRequest) {
  try {
    if (req.method !== "POST") {
      return NextResponse.json(
        { status: 405, message: "Method not allowed" },
        { status: 405 }
      );
    }

    const body = await req.json();
    const uuid = uuidv4();
    const cookies = req.cookies;
    const userId = cookies.get("userId");

    if (!userId) {
      return NextResponse.json(
        { status: 401, message: "Unauthorized" },
        { status: 401 }
      );
    }

    const productKey = `Product:${userId.value}:${uuid}`;

    const dataToStore = { uuid, ...body };
    const flattenedData: { [key: string]: any } = {};
    for (const [key, value] of Object.entries(dataToStore)) {
      flattenedData[key] =
        typeof value === "object" ? JSON.stringify(value) : value;
    }

    await client.HSET(productKey, flattenedData);

    return NextResponse.json(
      { status: 200, message: "Success" },
      { status: 200 }
    );
  } catch (error) {
    console.error("Error processing data:", error);
    return NextResponse.json(
      { status: 500, message: "Failed to process data" },
      { status: 500 }
    );
  }
}
Frontend:

"use client";
import { useEffect, useState } from "react";
import Image from "next/image";
import { usePathname } from "next/navigation";
import Shopify from "@/assets/shopify.png";
import { useSelector } from "react-redux";
import type { RootState } from "@/redux/store";

export default function Page() {
  const [dataStore, setDataStore] = useState<any[]>([]);
  const [product, setProduct] = useState<any | null>(null);
  const [userId, setUserId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [checkboxStates, setCheckboxStates] = useState<Record<string, boolean>>(
    {}
  );
  const pathname = usePathname();
  const { sku } = pathname;
  const selectedProduct = useSelector(
    (state: RootState) => state.products.selectedProduct
  );
  const uuid = selectedProduct?.data?.uuid;

  console.log(`selectedProduct${userId}:${uuid}`, "selected product rtk");

  if (!selectedProduct) {
    return <p>No product selected</p>;
  }
  const handleCheckboxChange = (storeId: string) => {
    setCheckboxStates((prevStates) => ({
      ...prevStates,
      [storeId]: !prevStates[storeId],
    }));
  };
  useEffect(() => {
    const id = localStorage.getItem("userId");
    setUserId(id);

    async function fetchStores() {
      try {
        const response = await fetch("/api/get-stores");
        const data = await response.json();
        if (data.stores) {
          const filteredStores = data.stores.filter(
            (store: any) => store.userid === id
          );
          console.log("this is the filtered data store", filteredStores);
          setDataStore(filteredStores);
        } else {
          console.error("Stores data not found in response");
        }
      } catch (error) {
        console.error("Failed to fetch stores", error);
      }
    }

    fetchStores();
  }, [userId]);

  useEffect(() => {
    const fetchProduct = async () => {
      if (!sku) return;

      console.log("Fetching product with SKU:", sku);

      try {
        const response = await fetch(`/api/getSku?sku=${sku}`);
        if (!response.ok)
          throw new Error(`HTTP error! status: ${response.status}`);

        const data = await response.json();
        console.log("Fetched product data:", data);

        setProduct(data);
      } catch (error) {
        setError(error.message);
      } finally {
        setLoading(false);
      }
    };

    fetchProduct();
  }, [sku]);

  if (error) return <p>Error: {error}</p>;
  const handleSubmit = async () => {
    try {
      const updatedProduct = {
        ...product,
        title: (document.getElementById("title") as HTMLInputElement).value,
        description: (
          document.getElementById("description") as HTMLTextAreaElement
        ).value,
      };
      const response = await fetch(
        `/api/products?userId=${userId}&uuid=${uuid}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(updatedProduct),
        }
      );

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      console.log("Product updated successfully");
    } catch (error) {
      setError(error.message);
    }
  };
  return (
    <div className="w-full mx-auto flex flex-col items-center justify-center">
      <div className="w-full xl:w-[1200px]">
        <div className="flex justify-center mt-10">
          <div className="w-full h-[200px] rounded-2xl border-2 px-16 flex items-center">
            <div className="mr-4">
              <Image
                src={
                  selectedProduct.data.imageUrl || selectedProduct.data.frontUrl
                }
                alt={selectedProduct.data.title || "Product Image"}
                className="w-[282px] h-[195px]"
                width={282}
                height={143}
              />
            </div>
            <div className="mx-8">
              <h3 className="text-lg font-semibold text-blue-600 mb-1">
                {selectedProduct.data.title || "Product Title"}
              </h3>
              <p className="text-sm text-gray-600 leading-normal mb-1">
                {selectedProduct.data.description || "Product Description"}
              </p>
              <p className="font-inter font-normal text-sm leading-4 text-[#888888] mb-0">
                {selectedProduct.data.sku || "SKU ID"}
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="flex flex-col lg:flex-row w-full xl:w-[1200px] gap-8 mt-10">
        <div className="w-full lg:w-[517px] mx-auto justify-center h-[335px] border-[#EEEEEE] border bg-[#F4F4F4] flex flex-col items-center rounded-2xl p-5 gap-8">
          <div className="flex flex-col justify-center w-full">
            <label className="font-inter font-medium text-[16px] leading-5 mb-2 text-[#111111]">
              Product Title
            </label>
            <input
              className="p-5 w-full lg:w-[469px] rounded-lg gap-[10px] font-inter font-medium text-[16px] leading-6 text-[#BDC1C6]"
              type="text"
              name="title"
              id="title"
              placeholder="Enter product Title"
              defaultValue={selectedProduct?.data?.title || ""}
            />
          </div>
          <div className="flex flex-col justify-center w-full">
            <label className="font-inter font-medium text-[16px] leading-5 text-[#111111] pb-3">
              Description
            </label>
            <textarea
              className="p-5 w-full lg:w-[469px] h-[140px] resize-none rounded-lg gap-[10px] font-inter font-medium text-[16px] leading-6 text-[#BDC1C6]"
              name="description"
              id="description"
              placeholder="Enter text..."
              defaultValue={selectedProduct?.data?.description || ""}
            />
          </div>
        </div>

        <div className="w-full lg:w-[643px] h-auto lg:h-[384px]">
          {dataStore.length > 0 ? (
            dataStore.map((store) => (
              <div
                key={store.id}
                className="flex items-center justify-between border rounded-2xl my-3 p-3"
              >
                <div className="flex items-center">
                  <div className="w-[282px] h-[80px]">
                    <Image
                      src={Shopify}
                      alt="shopify"
                      className="w-[170px] h-[70px]"
                      width={170}
                      height={70}
                    />
                  </div>
                  <div className="font-inter font-medium text-[15px] leading-6 text-[#202020] flex-grow w-[67px] h-[80px] flex justify-center items-center ml-8">
                    {store.shop}
                  </div>
                </div>
                <div>
                  <input
                    type="checkbox"
                    className="w-[19.2px] h-[19.2px] text-[#9AA0A6] mr-5"
                    checked={checkboxStates[store.id] || false}
                    onChange={() => handleCheckboxChange(store.id)}
                  />
                </div>
              </div>
            ))
          ) : (
            <p className="text-center text-gray-500">No stores available</p>
          )}
        </div>
      </div>
      <div className="flex justify-center">
        <button
          type="submit"
          className="mb-3 lg:mb-0 w-[200px] h-[40px] lg:w-[250px] lg:h-[48px] py-2 text-white bg-red-500 rounded-full hover:bg-red-600"
          onClick={handleSubmit}
        >
          Approve and publish
        </button>
      </div>
    </div>
  );
}

in this case it created a new hash table and contains the name description and uuid but i want to update with in the previous one

**Comment by usama7365** [comment]
You need to fetch the existing hash and update it with the new values. Here’s how you can modify your API and frontend code to achieve this:

### API Code

Modify your `POST` handler to update the existing Redis hash:

```typescript
import { client } from "@/lib/redis";
import { NextRequest, NextResponse } from "next/server";
import { v4 as uuidv4 } from "uuid";

export async function POST(req: NextRequest) {
  try {
    if (req.method !== "POST") {
      return NextResponse.json(
        { status: 405, message: "Method not allowed" },
        { status: 405 }
      );
    }

    const body = await req.json();
    const uuid = body.uuid || uuidv4(); // Use the provided UUID or generate a new one
    const cookies = req.cookies;
    const userId = cookies.get("userId");

    if (!userId) {
      return NextResponse.json(
        { status: 401, message: "Unauthorized" },
        { status: 401 }
      );
    }

    const productKey = `Product:${userId.value}:${uuid}`;

    // Fetch the existing hash
    const existingData = await client.HGETALL(productKey);

    // Merge existing data with the new data
    const updatedData = { ...existingData, ...body };

    // Flatten the data for storage
    const flattenedData: { [key: string]: any } = {};
    for (const [key, value] of Object.entries(updatedData)) {
      flattenedData[key] =
        typeof value === "object" ? JSON.stringify(value) : value;
    }

    await client.HSET(productKey, flattenedData);

    return NextResponse.json(
      { status: 200, message: "Success" },
      { status: 200 }
    );
  } catch (error) {
    console.error("Error processing data:", error);
    return NextResponse.json(
      { status: 500, message: "Failed to process data" },
      { status: 500 }
    );
  }
}
```

### Frontend Code

Modify the `handleSubmit` function to include the UUID and send the updated data to the API:

```javascript
const handleSubmit = async () => {
  try {
    const updatedProduct = {
      ...product,
      uuid: product.uuid, // Ensure UUID is included in the update
      title: (document.getElementById("title") as HTMLInputElement).value,
      description: (
        document.getElementById("description") as HTMLTextAreaElement
      ).value,
    };

    const response = await fetch(
      `/api/products?userId=${userId}&uuid=${uuid}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(updatedProduct),
      }
    );

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }

    console.log("Product updated successfully");
  } catch (error) {
    setError(error.message);
  }
};
```

### Explanation

1. **API Code**: 
   - The API now fetches the existing hash data using `HGETALL`.
   - It merges the existing data with the new data from the request.
   - It flattens the merged data and updates the Redis hash with `HSET`.

2. **Frontend Code**:
   - Ensure the UUID is included in the update payload.
   - The `handleSubmit` function sends the updated product data, including the UUID, to the API.

**Comment by Zainali005** [comment]
I have done it sorry for still open

**Comment by usama7365** [comment]
issue resolved 👌
