### ISSUE TITLE
getting Error in getMessages controller:  Cannot read properties of null (reading 'messages')

### ISSUE THREAD

**Issue by VisalRazaZaidi** [usama7365/developer-community#6]
**Describe the bug**
I'm getting an error when I'm trying to send get request from postman for sending message to other user 
what to do and why i'm getting this ?

**Screenshots**
![image](https://github.com/user-attachments/assets/3c3e6e07-5085-4b21-9aa7-560e76a6d95d)
![image](https://github.com/user-attachments/assets/1315ed36-2310-4640-9495-2d0a7b5b01a6)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser MS Edge

**Smartphone (please complete the following information):**

**Additional context**
I'm building an Chat App on MERN stack for project

**Comment by usama7365** [comment]
come anydesk let me figure out the problem @VisalRazaZaidi

**Comment by usama7365** [comment]
issue resolved

**Comment by usama7365** [comment]
issue resolved 👌
