### ISSUE TITLE
I am facing some issue with the tabs and dashboard code explain in description:

### ISSUE THREAD

**Issue by Zainali005** [usama7365/developer-community#8]
"use server";
import React from "react";
import Orders from "./Orders";
import { client } from "@/lib/redis";
import axios from "axios";
import { cookies } from "next/headers";
import Menu from "@/components/Menu";

function getLoggedInUserId() {
  const cookieStore = cookies();
  const userId = cookieStore.get("userId");
  return userId ? userId.value : null;
}

async function fetchOrders(loggedInUserId: any) {
  let orders = [];

  try {
    const keys = await client.keys(`order:${loggedInUserId}:*`);
    const redisOrdersData = await Promise.all(
      keys?.map((key) => client.get(key))
    );

    if (redisOrdersData.length > 0) {
      orders = redisOrdersData.map((data) => JSON.parse(data));
    } else {
      const storeKeys = await client.keys("store:*");
      const stores = await Promise.all(
        storeKeys.map((key) => client.hGetAll(key))
      );
      const fallbackImageUrl =
        "https://static.vecteezy.com/system/resources/thumbnails/022/014/063/small_2x/missing-picture-page-for-website-design-or-mobile-app-design-no-image-available-icon-vector.jpg";

      const userStores = stores.filter(
        (store) => store.userid === loggedInUserId
      );

      const fetchOrdersPromises = userStores.map(async (store) => {
        const requestOptions = {
          headers: {
            "Content-Type": "application/json",
            "X-Shopify-Access-Token": store.token,
          },
        };

        try {
          const response = await axios.get(
            `https://${store.shop}/admin/api/2024-01/orders.json`,
            requestOptions
          );
          const resp = response.data;
          if (!resp.orders || !Array.isArray(resp.orders)) {
            return [];
          }
          const storeOrders = await Promise.all(
            resp.orders.map(async (order: any) => {
              if (order.line_items.length > 0) {
                const url = `https://${store.shop}/admin/api/2024-01/products/${order.line_items[0].product_id}/images.json`;
                try {
                  const imageResponse = await axios.get(url, requestOptions);
                  const imgRes = imageResponse.data;
                  const imgSrc = imgRes.images[0]?.src || fallbackImageUrl;
                  order.fulfillment_status = order.fulfillment_status || null;
                  return { ...order, imgSrc };
                } catch {
                  return { ...order, imgSrc: fallbackImageUrl };
                }
              } else {
                return { ...order, imgSrc: fallbackImageUrl };
              }
            })
          );
          return storeOrders;
        } catch {
          return [];
        }
      });

      const fetchedOrders = await Promise.all(fetchOrdersPromises);
      orders = fetchedOrders.flat();
      await synchronizeOrders(orders, loggedInUserId);
    }
  } catch {
    return [];
  }

  const uniqueOrders = orders.filter(
    (order, index, self) => index === self.findIndex((o) => o.id === order.id)
  );

  return uniqueOrders;
}

async function synchronizeOrders(fetchedOrders: any, loggedInUserId: any) {
  try {
    const existingKeys = await client.keys(`order:${loggedInUserId}:*`);
    const existingOrdersData = await Promise.all(
      existingKeys.map((key) => client.get(key))
    );
    const existingOrders = existingOrdersData.map((data) => JSON.parse(data));
    const existingOrdersMap = new Map(
      existingOrders.map((order) => [order.id, order])
    );
    const ordersToUpdate = fetchedOrders.filter((order: any) => {
      const existingOrder = existingOrdersMap.get(order.id);
      return (
        !existingOrder ||
        JSON.stringify(existingOrder) !== JSON.stringify(order)
      );
    });

    const ordersToRemove = existingOrders.filter((existingOrder) => {
      return !fetchedOrders.find((order: any) => order.id === existingOrder.id);
    });
    const order = ordersToUpdate.map((order) => order.id);
    console.log(order);

    if (ordersToUpdate.length > 0) {
      for (const order of ordersToUpdate) {
        const orderKey = `orders:${loggedInUserId}:order:${order.id}`;
        const orderData = [];
        for (const key in order) {
          if (order.hasOwnProperty(key)) {
            orderData.push(key, JSON.stringify(order[key]));
          }
        }

        try {
          await client.HSET(orderKey, orderData);
        } catch (error) {
          console.error(`Error setting hash for order ${orderKey}:`, error);
        }
      }
    }

    if (ordersToRemove.length > 0) {
      for (const order of ordersToRemove) {
        await client.del(`order:${loggedInUserId}:${order.id}`);
      }
    }
  } catch (error) {
    console.error("Error synchronizing orders:", error);
  }
}

export default async function Page() {
  const loggedInUserId = getLoggedInUserId();

  if (!loggedInUserId) {
    return (
      <div>
        <Menu selectedTab="new" setSelectedTab={() => {}} />
        <p className="flex justify-center text-3xl text-red-600 font-inter font-bold">
          User not logged in!
        </p>
      </div>
    );
  }

  const orders = await fetchOrders(loggedInUserId);

  return <Orders orders={orders} />;
}

Tab.tsx:
"use client";
import React, { useEffect, useState } from "react";
import StoreRow from "@/components/StoreRow";
import Menu from "@/components/Menu";

export default function Orders({ orders }: any) {
  const [selectedTab, setSelectedTab] = useState("new");
  const [filteredOrders, setFilteredOrders] = useState([]);

  useEffect(() => {
    const filterOrders = () => {
      switch (selectedTab) {
        case "new":
          return orders.filter(
            (order: any) =>
              !order.fulfillment_status || order.fulfillment_status === "new"
          );
        case "in-progress":
          return orders.filter(
            (order: any) => order.fulfillment_status === "in_progress"
          );
        case "in-transit":
          return orders.filter(
            (order: any) => order.fulfillment_status === "in-transit"
          );
        case "complete":
          return orders.filter(
            (order: any) => order.fulfillment_status === "complete"
          );
        default:
          return orders;
      }
    };

    const filteredOrders = filterOrders();
    setFilteredOrders(filteredOrders);
  }, [selectedTab, orders]);

  return (
    <div>
      <Menu selectedTab={selectedTab} setSelectedTab={setSelectedTab} />
      {filteredOrders.length > 0 ? (
        filteredOrders.map((order, index) => (
          <StoreRow store={order} key={index} />
        ))
      ) : (
        <div className="flex justify-center items-center h-[70vh]">
          <p className="font-inter text-2xl leading-36px tracking--1.9% font-medium text-center leading-[21.78px]">
            No orders found in {selectedTab}!
          </p>
        </div>
      )}
    </div>
  );
}

I am facing issue i have store the order in redis database the issue is when i changed the fullfillment_status to "in_progress,in-transit and complete" and refresh to check the order showing the relevant tab or not it again changed to null:

**Comment by usama7365** [comment]
When updating the fulfillment_status of an order, ensure that the updated order data is correctly written back to Redis. Check the synchronizeOrders function to verify that the data being written is accurate and complete.
```

async function synchronizeOrders(fetchedOrders: any, loggedInUserId: any) {
    try {
        const existingKeys = await client.keys(`order:${loggedInUserId}:*`);
        const existingOrdersData = await Promise.all(
            existingKeys.map((key) => client.get(key))
        );
        const existingOrders = existingOrdersData.map((data) => JSON.parse(data));
        const existingOrdersMap = new Map(
            existingOrders.map((order) => [order.id, order])
        );

        const ordersToUpdate = fetchedOrders.filter((order: any) => {
            const existingOrder = existingOrdersMap.get(order.id);
            return (
                !existingOrder ||
                JSON.stringify(existingOrder) !== JSON.stringify(order)
            );
        });

        const ordersToRemove = existingOrders.filter((existingOrder) => {
            return !fetchedOrders.find((order: any) => order.id === existingOrder.id);
        });

        // Update or add orders
        if (ordersToUpdate.length > 0) {
            for (const order of ordersToUpdate) {
                const orderKey = `order:${loggedInUserId}:${order.id}`;
                const orderData: string[] = [];
                for (const key in order) {
                    if (order.hasOwnProperty(key)) {
                        orderData.push(key, JSON.stringify(order[key]));
                    }
                }

                try {
                    await client.HSET(orderKey, orderData);
                } catch (error) {
                    console.error(`Error setting hash for order ${orderKey}:`, error);
                }
            }
        }

        // Remove orders that no longer exist
        if (ordersToRemove.length > 0) {
            for (const order of ordersToRemove) {
                await client.del(`order:${loggedInUserId}:${order.id}`);
            }
        }
    } catch (error) {
        console.error("Error synchronizing orders:", error);
    }
}


```
**Double-check fulfillment_status Updates:**

Verify that the fulfillment_status is correctly updated both in the fetched orders and in Redis. Ensure that when an order's status is updated in the system, this change is reflected in Redis.
Ensure Frontend Component Reactivity:

In your Orders component, make sure that the useEffect hook is correctly triggering when orders or selectedTab changes. This should correctly filter and display the orders in the relevant tab.

```

useEffect(() => {
    const filterOrders = () => {
        switch (selectedTab) {
            case "new":
                return orders.filter(
                    (order: any) =>
                        !order.fulfillment_status || order.fulfillment_status === "new"
                );
            case "in-progress":
                return orders.filter(
                    (order: any) => order.fulfillment_status === "in_progress"
                );
            case "in-transit":
                return orders.filter(
                    (order: any) => order.fulfillment_status === "in-transit"
                );
            case "complete":
                return orders.filter(
                    (order: any) => order.fulfillment_status === "complete"
                );
            default:
                return orders;
        }
    };

    const filteredOrders = filterOrders();
    setFilteredOrders(filteredOrders);
}, [selectedTab, orders]);


```
Log Order Data:

Add console logs within the synchronizeOrders function to check if the orders being stored in Redis are correct.
Log the orders in the frontend to ensure that they are being received correctly with the updated fulfillment_status.

**Comment by Zainali005** [comment]
i have checked every thing the issue i tackle is this when i reload after updating the fullfullment status to check the order is showing in different tabs or not then in the redis db the changed fullfillment status to null
At the same time when i check the condition if the order is available in the redis then not store then its working but the new or cancel orders not showing . That's the main problem

**Comment by usama7365** [comment]
Hi @Zainali005,

It sounds like you're facing an issue where the `fulfillment_status` is reverting to `null` after refreshing the page, which affects how orders are displayed in different tabs.

Here's a possible solution:

### 1. **Ensure Proper Data Synchronization**
   - Double-check that the `synchronizeOrders` function is correctly saving the updated `fulfillment_status` back to Redis. Specifically, verify that the orders with updated statuses are not being overwritten with old data from Redis.

### 2. **Debugging and Logs**
   - Add more `console.log` statements in both the `synchronizeOrders` function and in the frontend `useEffect` hook to trace the data flow. Check whether the `fulfillment_status` is properly updated before and after the synchronization with Redis.

### 3. **Avoid Overwriting with Null Values**
   - It might be helpful to adjust your logic to prevent overwriting the `fulfillment_status` with `null` during synchronization. Before updating an order in Redis, ensure the data you're writing back is accurate and that `null` values are not being inadvertently introduced.

### 4. **Refactor Condition Handling**
   - If you're conditionally checking whether an order exists in Redis and preventing it from being stored again, make sure this logic doesn't skip over orders that need to be updated or added. You might need to refine the condition to handle new and canceled orders properly.

```javascript
// Add more logging to diagnose where the fulfillment_status might be getting reset
console.log("Orders before saving to Redis:", ordersToUpdate);
console.log("Orders being removed:", ordersToRemove);
```

### 5. **Check Order State Across Tabs**
   - Ensure the filtering logic in your `Orders` component's `useEffect` is correctly filtering based on the `fulfillment_status` and that the data you receive from Redis reflects the most recent state.

### 6. **Testing Scenarios**
   - Test different scenarios, such as updating the order status and immediately fetching the updated status from Redis to ensure consistency.

Let me know if these steps help or if you need further assistance!

Best,
Usama Aamir
